name: Build LaTeX and deploy on GitHub Releases
on:
  check_run:
  check_suite:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  update-acmart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: action/checkout@v3.0.2
        with:
          ref: master
          fetch-depth: 0
          submodules: recursive
      - name: Cleanup the repository
        run: rm -rf *
      - name: Download the latest acmart
        run: curl --retry 50 https://www.acm.org/binaries/content/assets/publications/consolidated-tex-template/acmart-primary.zip --output acmart.zip
      - name: Unzip the archive
        run: |
          7z x acmart.zip
          mv acmart-primary/* .
      - name: Cleanup the directory
        run: |
          rm acmart.zip
          rm -r acmart-primary/*
          rm -r acmart-primary/.*
      - name: Configure git
        run: |
          git config --global user.name "acmart-updater[bot]"
          git config --global user.email "noreply@danysk.github.io"
      - run: git add .
      - run: 'git commit -m "chore: update acmart"'
      - run: git push
