name: Update acmart
on:
  check_run:
  check_suite:
  pull_request:
  push:
  workflow_dispatch:


jobs:
  update-acmart:
    if: contains(github.repository, 'Template-LaTeX-acmart')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.1
        with:
          ref: master
          fetch-depth: 0
          submodules: recursive
      - name: Cleanup the repository
        run: rm -rf *
      - name: Download the latest acmart
        run: curl -A "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/81.0" -sL --retry 50 'https://portalparts.acm.org/hippo/latex_templates/acmart-primary.zip' --output acmart.zip
      - name: Unzip the archive
        run: |
          7z x acmart.zip
          mv acmart-primary/* .
      - name: Cleanup the directory
        run: |
          rm -rf acmart-primary
          rm acmart.zip
          rm samples/sample-acmcp.tex
          git checkout HEAD -- renovate.json
      - name: Configure git
        run: |
          git config --global user.name "acmart-updater[bot]"
          git config --global user.email "noreply@danysk.github.io"
      - run: git add .
      - run: 'git diff --staged --quiet || git commit -m "chore: update acmart"'
      - run: git push
